from typing import TypedDict, Optional, List
from datetime import datetime

class RecoveryState(TypedDict):
    # Invoice context
    invoice_id: int
    client_name: str
    client_email: str
    amount: float
    due_date: str
    current_status: str
    days_overdue: int
    escalation_stage: str            # STAGE_1, STAGE_2, STAGE_3, STAGE_4
    last_email_date: Optional[str]
    virtual_date: Optional[str]

    # Client reply (if any)
    client_reply: Optional[str]

    # Agent working memory
    classified_intent: Optional[str]  # PROMISE_TO_PAY, DISPUTE, OPT_OUT, etc.
    intent_confidence: Optional[float]
    extracted_entities: Optional[dict] # promised_date, disputed_amount, reason

    # RAG-retrieved context
    retrieved_context: Optional[str]  # Contract terms, past interactions, notes

    # Draft & Compliance loop
    drafted_email: Optional[str]
    compliance_verdict: Optional[str] # PASS or FAIL
    compliance_reason: Optional[str]
    compliance_retries: int           # Max 2 rewrites

    # Razorpay tool results
    payment_link_url: Optional[str]   # Generated by MCP create_payment_link
    virtual_account_details: Optional[dict]  # From Smart Collect

    # Execution
    action_taken: Optional[str]
    new_status: Optional[str]
    rule_applied: Optional[str]       # Which compliance rule governed the decision

    # Audit accumulator
    audit_entries: List[dict]

    # Flow control
    should_send_email: bool
